# Generated by Django 5.0.6 on 2025-07-14 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recorrido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('estado', models.CharField(max_length=50)),
                ('ciudad', models.CharField(max_length=50)),
                ('kilometros', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tiempo_estimado', models.DurationField()),
                ('punto_inicio', models.CharField(max_length=100)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=8)),
                ('descripcion', models.TextField()),
                ('fotografia', models.ImageField(blank=True, null=True, upload_to='recorridos_fotos/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
