# Generated by Django 5.0.6 on 2025-07-14 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recorridos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recorridos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=100, verbose_name='Estado del Recorrido')),
            ],
            options={
                'verbose_name': 'Estado del Recorrido',
                'verbose_name_plural': 'Estados de los Recorridos',
            },
        ),
        migrations.AlterModelOptions(
            name='recorrido',
            options={'ordering': ['-fecha', '-hora'], 'verbose_name': 'Recorrido', 'verbose_name_plural': 'Recorridos'},
        ),
        migrations.AlterField(
            model_name='recorrido',
            name='fotografia',
            field=models.ImageField(null=True, upload_to='fotos/', verbose_name='Fotografia'),
        ),
    ]
