# Generated by Django 5.0.6 on 2025-07-14 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recorridos', '0002_recorridos_alter_recorrido_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preinscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('ciudad', models.CharField(max_length=50, verbose_name='Ciudad')),
                ('estado', models.CharField(max_length=50, verbose_name='Estado')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('recorrido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recorridos.recorrido', verbose_name='Recorrido')),
            ],
            options={
                'verbose_name': 'Preinscripción',
                'verbose_name_plural': 'Preinscripciones',
                'ordering': ['-created'],
            },
        ),
    ]
